title: Matheus Kunzler Maldaner
tagline: Master's Student and Researcher
url: https://matheus.wiki
baseurl: "/cv"
# data_dir: ../data
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Matheus Kunzler Maldaner
  url: http://matheus.wiki
  email: mkunzlermaldaner@ufl.edu

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Feed settings
feed:
  posts_limit: 50
